### ISSUE TITLE
(Partial) support for the web version of VS Code?

### ISSUE THREAD

**Issue by Speeder323** [DenizenScript/DenizenVSCode#10]
![image](https://github.com/DenizenScript/DenizenVSCode/assets/61844671/f897174a-9eec-42ed-8c97-7dac1342923e)
I don't know how much it takes to do this, but I wanted to send this here in case you can make it happen.

**Comment by mcmonkey4eva** [comment]
Not possible unfortunately. Web version is too restrictive.
