### ISSUE TITLE
Ideas for the rewrite

### ISSUE THREAD

**Issue by waterquarks** [DenizenScript/DenizenVSCode#2]
- Introduce code templates, for commands it is a must (tag autocomplete would be handy too).
- In order to avoid quote spam, highlight the name of each argument in the commands.
- Highlight `null` in red, other special values should have their own color too.
- Make the command names not italic.
- Support the light theme! Trying to use it along with the Denizen color scheme causes weird issues.

**Comment by mcmonkey4eva** [comment]
Don't spam nonsense issues please.
