### ISSUE TITLE
Extension Error Issue

### ISSUE THREAD

**Issue by kennykantisiri** [DenizenScript/DenizenVSCode#3]
Hello there,

I am using the DenizenVSCode Extension. I have faced an issue where if I use type assignment in a script, and don't include "interact scripts", it will underline it in red and say "Missing required key `interact scripts`", even though the documentation says "All part of an assignment script are optional."

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
