### ISSUE TITLE
(Warning) Stray space after end of line (possible copy/paste mixup. Enable View->Render Whitespace in VS Code).

### ISSUE THREAD

**Issue by aTyCuH** [DenizenScript/DenizenVSCode#5]
after reload vs i always take that error
(Warning) Stray space after end of line (possible copy/paste mixup. Enable View->Render Whitespace in VS Code).  

![image](https://user-images.githubusercontent.com/25547556/109417672-481c4180-79cd-11eb-81a3-7f712f277e33.png)
![image](https://user-images.githubusercontent.com/25547556/109417693-61bd8900-79cd-11eb-83b5-2293b1f43888.png)

**Comment by aTyCuH** [comment]
i want add what follow instalion guide here:
https://guide.denizenscript.com/guides/first-steps/script-editor.html

**Comment by mcmonkey4eva** [comment]
Support is on Discord @ https://discord.gg/Q6pZGSR
